version: "3.9"
services:
  web:
    image: python:3
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - .:/app
    command:
      - pip install -r requirments.txt
      - python app.py