version: "3.9"
services:
  web:
    image: python:3
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install -r requirements.txt && python app.py" 